    const events = [
      {
        startDate: '2026-03-18',
        endDate: '2026-03-18',
        eventType: 'Weekly seminar',
        category: ['Talk'],
        isTalk: true,
        location: 'Institut de Mathématiques de Toulouse',
        eventName: 'Quid Seminar',
        role: 'Speaker',
        title: 'First steps in symplectic dynamics',
        duration: '1h talk'
      },
      {
        startDate: '2026-03-13',
        endDate: '2026-03-13',
        eventType: 'Compact Course',
        category: 'Compact Course',
        isTalk: false,
        location: 'Open for You! 4EU+webinar',
        eventName: 'Open science 101: Principles, practices and challenges',
        role: 'Participant'
      },
      {
        startDate: '2025-02-16',
        endDate: '2025-02-20',
        eventType: 'Workshop',
        category: ['Attendance'],
        isTalk: false,
        location: 'Institut Henri Poincaré, Paris',
        eventName: 'Bridging Visualisation and Understanding in Geometry: Illustration as a Mathematical Research Technique',
        role: 'Attendee',
        },  
      {
        startDate: '2025-12-10',
        endDate: '2025-12-10',
        eventType: 'Weekly seminar',
        category: ['Talk'],
        isTalk: true,
        location: 'Laboratoire de Mathématiques Jean Leray (LMJL), Nantes',
        eventName: 'PhD Students’ Seminar',
        role: 'Speaker',
        title: 'Un aperçu des questions actuelles en systèmes dynamiques',
        duration: '1h talk'
        },
        {
        startDate: '2025-12-04',
        endDate: '2025-12-04',
        eventType: 'Weekly seminar',
        category: ['Talk'],
        isTalk: true,
        location: 'Institut de recherche mathématique de Rennes (IRMAR)',
        eventName: 'Pampers Seminar',
        role: 'Speaker',
        title: 'Un tour en dynamique symplectique',
        duration: '1h talk'
        },
        {
        startDate: '2025-11-17',
        endDate: '2025-11-17',
        eventType: 'Weekly Seminar',
        category: ['Talk'],
        isTalk: true,
        location: 'Universität Augsburg',
        eventName: '<a href="https://www.math.uni-augsburg.de/htdocs/VK/docs/2025/11/17_Mo_47_00.html" target="_blank">Oberseminar Differentialgeometrie</a>',
        role: 'Speaker',
        title: 'On the Contact Type Conjecture for Exact Magnetic Systems',
        duration: '1h talk'
        },
        {
        startDate: '2025-09-22',
        endDate: '2025-09-26',
        eventType: 'Conference',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'bifeb, Strobl',
        eventName: 'ISTA Summer School in Dynamical Systems',
        role: 'Speaker',
        title: 'Periodic Orbits and Contact Type Property in High-Dimensional Magnetic Systems',
        duration: '15min talk'
        },
        {
        startDate: '2025-08-25',
        endDate: '2025-08-29',
        eventType: 'Conference',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'Université de Bordeaux',
        eventName: 'Conformal Dynamics and Geometry',
        role: 'Speaker',
        title: 'Periodic Orbits and Contact Type Property in High-Dimensional Magnetic Systems',
        duration: '25min talk'
        },
        {
        startDate: '2025-07-14',
        endDate: '2025-07-18',
        eventType: 'Workshop',
        category: ['Attendance','Organization'],
        isTalk: false,
        location: 'Universität Heidelberg',
        eventName: 'Workshop: Billiards and quantitative symplectic geometry',
        role: 'Organizer',
      },
        {
        startDate: '2025-06-16',
        endDate: '2025-06-20',
        eventType: 'Summer School',
        category: 'Attendance',
        isTalk: false,
        location: 'Cetraro',
        eventName: 'Summer School: Symplectic Dynamics and Topology',
        role: 'Attendee',
      },
      {
        startDate: '2025-06-02',
        endDate: '2025-06-06',
        eventType: 'Summer School',
        category: 'Attendance',
        isTalk: false,
        location: 'CIRM',
        eventName: 'Summer School: Dynamics and geometry in dimension 1, 2 and 3',
        role: 'Attendee',
      },
      {
        startDate: '2025-03',
        endDate: '2025-07',
        eventType: 'Weekly Seminar',
        category: ['Attendance','Talk','Organization'],
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'Topics Seminar: A survey on Billiards',
        role: 'Speaker',
        title: 'An introduction to Symplectic Billiards: Questions on Integrability and Periodic orbits',
        duration: '1h talk'
      },
      {
        startDate: '2025-05-16',
        endDate: '2025-05-16',
        eventType: 'Compact Course',
        category: 'Compact Course',
        isTalk: false,
        location: 'Universität Heidelberg',
        eventName: '3D Printing and Laser Cutting Workshop',
        role: 'Participant'
      },
      {
        startDate: '2025-05-21',
        endDate: '2025-05-21',
        eventType: 'Weekly Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'Weekly Symplectic Seminar',
        role: 'Speaker',
        title: 'The Contact Type property for Killing Magnetic systems (jw L. Maier, T. Stalljohann)',
        duration: '1h talk'
      },
      {
        startDate: '2025-04-25',
        endDate: '2025-04-25',
        eventType: 'Seminar',
        category: 'Attendance',
        isTalk: false,
        location: 'RUB, Bochum',
        eventName: 'BACH Seminar',
        role: 'Attendee'
      },
      {
        startDate: '2025-02-24',
        endDate: '2025-02-26',
        eventType: 'Seminar',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'KIT, Karlsruhe',
        eventName: 'RTG2229 PhD Thematic Seminar: Elliptic PDEs',
        role: 'Speaker',
        title: 'Analytic PDE theory applied to a proof of an Uniformization Theorem',
        duration: '1h talk'
      },
      {
        startDate: '2025-02-06',
        endDate: '2025-02-28',
        eventType: 'Conference',
        category: 'Attendance',
        isTalk: false,
        location: 'Institut Fourier, Grenoble',
        eventName: 'CAST',
        role: 'Attendee'
      },
      {
        startDate: '2025-01-27',
        endDate: '2025-01-31',
        eventType: 'Thematic Program',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'ESI, Wien',
        eventName: 'Thematic Program: "Infinite dimensional Geometry. Week 3: Homeomorphisms of S^1 and Groups in infinite-dimensions "',
        role: 'Speaker',
        title: 'On a hyperkähler view of the magnetic geodesic flow on CP^n',
        duration: '20 min talk'
      },
      {
        startDate: '2025-01-07',
        endDate: '2025-01-07',
        eventType: 'Weekly Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'LAREMA, Angers',
        eventName: 'Weekly PhD Student Seminar',
        role: 'Speaker',
        title: 'Magnetic geodesics decribed by Quaternions on the 2-sphere (and CP^n?)',
        duration: '1h talk'
      },
      {
        startDate: '2024-12-18',
        endDate: '2024-12-18',
        eventType: 'Weekly Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'LMJL, Nantes',
        eventName: 'Weekly PhD Student Seminar',
        role: 'Speaker',
        title: 'Magnetic geodesics decribed by Quaternions on the 2-sphere (and CP^n?)',
        duration: '1h talk'
      },
      {
        startDate: '2024-12-12',
        endDate: '2024-12-12',
        eventType: 'Weekly Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'IRMAR, Rennes',
        eventName: 'Weekly PhD Student Seminar: Pampers Seminar',
        role: 'Speaker',
        title: 'Magnetic geodesics decribed by Quaternions on the 2-sphere (and CP^n?)',
        duration: '1h talk'
      },
      {
        startDate: '2024-12-09',
        endDate: '2024-12-09',
        eventType: 'Colloquium',
        category: 'Talk',
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'HGS Membership Colloqium',
        role: 'Speaker',
        title: 'On a hyperkähler view of the magnetic geodesic flow on CP^n',
        duration: '15 min talk'
      },
      {
        startDate: '2024-11-22',
        endDate: '2024-11-23',
        eventType: 'Colloquium',
        category: 'Attendance',
        isTalk: false,
        location: 'Universität zu Köln',
        eventName: 'Geometric Dynamical days',
        role: 'Attendee'
      },
      {
        startDate: '2024-11-14',
        endDate: '2024-11-15',
        eventType: 'Compact Course',
        category: 'Compact Course',
        isTalk: false,
        location: 'Universität Heidelberg',
        eventName: 'Interactive Theorem Proving in Lean, by Florent Schaffhauser',
        role: 'Participant'
      },
      {
        startDate: '2024-11-05',
        endDate: '2024-11-05',
        eventType: 'Special Guest Afternoon',
        category: 'Attendance',
        isTalk: false,
        location: 'Universität Heidelberg',
        eventName: 'A Stellar Afternoon in Symplectic Dynamics',
        role: 'Attendee'
      },
      {
        startDate: '2024-10-07',
        endDate: '2024-10-08',
        eventType: 'Retreat',
        category: 'Attendee',
        isTalk: false,
        location: 'Pforzheim',
        eventName: 'RTG2229 Retreat',
        role: 'Participant'
      },
      {
        startDate: '2024-09-16',
        endDate: '2024-09-20',
        eventType: 'Conference',
        category: 'Attendance',
        isTalk: false,
        location: 'RWTH, Aachen',
        eventName: 'Symplectic Dynamics in Aachen',
        role: 'Attendee'
      },
      {
        startDate: '2024-07-22',
        endDate: '2024-07-26',
        eventType: 'Workshop',
        category: 'Attendance',
        isTalk: false,
        location: 'Universität Heidelberg',
        eventName: 'Symplectic Geometry and Anosov Flows',
        role: 'Attendee'
      },
      {
        startDate: '2024-07-05',
        endDate: '2024-07-05',
        eventType: 'Seminar',
        category: 'Attendance',
        isTalk: false,
        location: 'RUB, Bochum',
        eventName: 'BACH Seminar',
        role: 'Attendee'
      }, 
      {
        startDate: '2024-06-17',
        endDate: '2024-06-21',
        eventType: 'Summer School',
        category: 'Attendance',
        isTalk: false,
        location: 'ICMAT, Madrid',
        eventName: 'Summer School on h-principle',
        role: 'Attendee',
      }, 
      {
        startDate: '2024-06-06',
        endDate: '2024-06-07',
        eventType: 'Site Visit',
        category: 'Talk',
        isTalk: true,
        location: 'RUB, Bochum',
        eventName: 'SFB CRC/TRR191 Site Visit',
        role: 'Poster Commentary',
        title: 'Poster commentary on project A8: Symplectic geometry of representation and quiver varieties'
      },
      {
        startDate: '2024-05-27',
        endDate: '2024-05-27',
        eventType: 'Student Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'Lectures on Dynamical systems',
        role: 'Speaker',
        title: 'Local invariant manifolds from a differentiable point of view',
        duration: '1h talk'
      },
      {
        startDate: '2024-05-08',
        endDate: '2024-05-08',
        eventType: 'Weekly Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'Weekly Symplectic Seminar',
        role: 'Speaker',
        title: 'On a hyperkähler view of the magnetic geodesic flow on CP^n',
        duration: '1h talk'
      },
      {
        startDate: '2024-04-24',
        endDate: '2024-04-24',
        eventType: 'Weekly Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'Weekly Topics Seminar',
        role: 'Speaker',
        title: 'Overview on my current research',
        duration: '20 min talk'
      }, //should add the topics seminar on hprinciple
      {
        startDate: '2024-04-19',
        endDate: '2024-04-19',
        eventType: 'Seminar',
        category: 'Attendance',
        isTalk: false,
        location: 'Universität Heidelberg',
        eventName: 'BACH Seminar',
        role: 'Attendee'
      },
      {
        startDate: '2024-03-11',
        endDate: '2024-03-15',
        eventType: 'Seminar',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'RTG2229 PhD Thematic Seminar: Morse Theory',
        role: 'Speaker',
        title: 'Homotopy Type: On the topology of sublevel sets',
        duration: '1h talk'
      },
      {
        startDate: '2024-02-08',
        endDate: '2024-02-10',
        eventType: 'Conference',
        category: 'Attendance',
        isTalk: false,
        location: 'RUB, Bochum',
        eventName: 'CAST',
        role: 'Attendee'
      },
      {
        startDate: '2024-01-31',
        endDate: '2024-02-01',
        eventType: 'Workshop',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'MPI Leipzig',
        eventName: 'SFB CRC/TRR191 project A8 Workshop: Symplectic geometry of representation and quiver varieties',
        role: 'Speaker',
        title: 'How quaternions describe the magnetic geodesic flow on the 2-sphere',
        duration: '20 min talk'
      },
      {
        startDate: '2023-12-12',
        endDate: '2023-12-12',
        eventType: 'Weekly Seminar',
        category: 'Talk',
        isTalk: true,
        location: 'LMJL, Nantes',
        eventName: 'Weekly PhD Student Seminar',
        role: 'Speaker',
        title: 'Periodic Trajectories in a Billiard Table',
        duration: '1h talk'
      },
      {
        startDate: '2023-10-20',
        endDate: '2023-10-20',
        eventType: 'Student Seminar',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'Student Seminar: Classical and Symplectic Billiards',
        role: 'Speaker',
        title: 'Periodic Trajectories in a Billiard Table',
        duration: '1h talk'
      },
      {
        startDate: '2023-10-20',
        endDate: '2023-10-20',
        eventType: 'Seminar',
        category: 'Attendance',
        isTalk: false,
        location: 'Universität zu Köln',
        eventName: 'BACH Seminar',
        role: 'Attendee'
      },
      {
        startDate: '2023-10-02',
        endDate: '2023-10-06',
        eventType: 'Retreat',
        category: ['Attendance','Talk'],
        isTalk: true,
        location: 'Universität Heidelberg',
        eventName: 'PhD Student Retreat',
        role: 'Speaker',
        title: 'On the Toeplitz Conjecture',
        duration: '1h talk'
      },
      {
        startDate: '2023-07-06',
        endDate: '2023-07-06',
        eventType: 'Workshop',
        category: 'Attendance',
        isTalk: false,
        location: 'Marsilius-Arkaden, Heidelberg',
        eventName: 'Mercator Workshop',
        role: 'Attendee',
      } //add first symplectic seminar maybe
    ];

